TRAIN:
  ENABLE: True
  DATASET: ESC50
  BATCH_SIZE: 32
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 30
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
  AUTO_RESUME: False
AUDIO_DATA:
  CLIP_SECS: 1.999
  NUM_FRAMES: 512
  INPUT_CHANNEL_NUM: [1]
ESC:
  FREQM: 24 # 0
  TIMEM: 96 # 0
  MIXUP: 0
  NUM_MELBINS: 128
  AUDIO_LENGTH: 512
  MEAN: -6.6268077
  STD: 5.358466
  SKIP_NORM: False
  NOISE: False
  MODE: train # evaluation
  LABEL_CSV: /home/s2/juanyeo/laalaudio/data/esc50/esc_class_labels_indices.csv
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 20]
  LRS: [1, 0.05, 0.01]
  MAX_EPOCH: 25
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 2.0
  WARMUP_START_LR: 1e-6
  OPTIMIZING_METHOD: adamw
TEST:
  ENABLE: False
  DATASET: ESC50
  BATCH_SIZE: 48
  NUM_ENSEMBLE_VIEWS: 5
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
MODEL:
  ARCH: ssast
  MODEL_NAME: SSASTModel
  NUM_CLASSES: [50]
  LOSS_FUNC: cross_entropy
SSAST:
  TASK: ft_cls
  PRETRAIN_STAGE: False
  FSTRIDE: 10
  TSTRIDE: 10
WANDB:
  ENABLE: False
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
